from typing import List, Dict, Any

ADDITIONAL_MAHARASHTRA_COLLEGES: List[Dict[str, Any]] = [
    {
        "id": "cummins-pune",
        "name": "MKSSS's Cummins College of Engineering for Women (CCOEW Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Karvenagar, Pune, Maharashtra",
        "type": "Private Autonomous (All-Women)",
        "rating": 4.6,
        "nirf_rank": 125,
        "established": 1991,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Girls Hostels with Mess & Wi-Fi)",
        "fees": 175000,
        "fee_display": "₹1.75 Lakh / year",
        "placement_avg": "₹10.5 LPA",
        "highest_package": "₹44.0 LPA",
        "top_recruiters": ["Goldman Sachs", "Microsoft", "Amazon", "Citi", "Barclays", "TCS"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering"
        ],
        "highlights": "MKSSS's Cummins College of Engineering for Women in Karvenagar, Pune, is India's premier autonomous women's engineering institution with outstanding placements in global tech corporations.",
        "base_cutoff": 94.80,
    },
    {
        "id": "kjsce-mumbai",
        "name": "K. J. Somaiya College of Engineering (KJSCE Mumbai)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Vidyavihar, Mumbai, Maharashtra",
        "type": "Private Autonomous / Deemed",
        "rating": 4.5,
        "nirf_rank": 130,
        "established": 1983,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Separate Boys & Girls Hostels with Mess)",
        "fees": 350000,
        "fee_display": "₹3.5 Lakh / year",
        "placement_avg": "₹9.8 LPA",
        "highest_package": "₹40.0 LPA",
        "top_recruiters": ["JPMorgan Chase", "Morgan Stanley", "Barclays", "Accenture", "TCS"],
        "exams": ["MHT-CET", "JEE Main", "PERA CET"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering"
        ],
        "highlights": "K. J. Somaiya College of Engineering in Vidyavihar, Mumbai, is a renowned autonomous engineering college established in 1983, featuring state-of-the-art campus infrastructure and strong corporate ties.",
        "base_cutoff": 94.00,
    },
    {
        "id": "mit-wpu",
        "name": "MIT World Peace University (MIT-WPU Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Kothrud, Pune, Maharashtra",
        "type": "Private Deemed University",
        "rating": 4.5,
        "nirf_rank": 110,
        "established": 1983,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Separate Boys & Girls Hostels with Wi-Fi)",
        "fees": 310000,
        "fee_display": "₹3.1 Lakh / year",
        "placement_avg": "₹8.5 LPA",
        "highest_package": "₹44.1 LPA",
        "top_recruiters": ["Amazon", "Microsoft", "TCS", "Infosys", "Wipro", "Tech Mahindra"],
        "exams": ["MHT-CET", "JEE Main", "MIT-WPU CET"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "MIT World Peace University in Kothrud, Pune, is an esteemed private research university offering world-class engineering education and holistic student development.",
        "base_cutoff": 93.20,
    },
    {
        "id": "vesit-mumbai",
        "name": "Vivekanand Education Society's Institute of Technology (VESIT Chembur)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Chembur, Mumbai, Maharashtra",
        "type": "Private Autonomous (Sindhi Minority)",
        "rating": 4.5,
        "nirf_rank": 142,
        "established": 1984,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Separate Boys & Girls Hostels)",
        "fees": 130000,
        "fee_display": "₹1.3 Lakh / year",
        "placement_avg": "₹7.8 LPA",
        "highest_package": "₹30.0 LPA",
        "top_recruiters": ["Nomura", "Morgan Stanley", "JPMorgan", "Accenture", "TCS", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Instrumentation Engineering"
        ],
        "highlights": "VESIT Chembur is a premier autonomous engineering college in Mumbai known for rigorous academic standards, exemplary coding culture, and stellar placements.",
        "base_cutoff": 92.50,
    },
    {
        "id": "viit-pune",
        "name": "Vishwakarma Institute of Information Technology (VIIT Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Kondhwa Budruk, Pune, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.4,
        "nirf_rank": 160,
        "established": 2002,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Separate Boys & Girls Hostels with Mess)",
        "fees": 165000,
        "fee_display": "₹1.65 Lakh / year",
        "placement_avg": "₹7.5 LPA",
        "highest_package": "₹34.0 LPA",
        "top_recruiters": ["Nvidia", "TCS", "Infosys", "Cognizant", "Persistent", "Accenture"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Civil Engineering"
        ],
        "highlights": "VIIT Kondhwa is a sister institute of VIT Pune, offering autonomous curriculum, top-notch labs, and strong placement track record in software and analytics.",
        "base_cutoff": 91.00,
    },
    {
        "id": "kjsieit-sion",
        "name": "K. J. Somaiya Institute of Technology (KJSIEIT Sion)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Sion, Mumbai, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.4,
        "established": 2001,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostel with Mess & Wi-Fi)",
        "fees": 160000,
        "fee_display": "₹1.6 Lakh / year",
        "placement_avg": "₹7.2 LPA",
        "highest_package": "₹28.0 LPA",
        "top_recruiters": ["LTI", "Infosys", "TCS", "Accenture", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication"
        ],
        "highlights": "KJSIEIT Sion is a well-established autonomous institution in Mumbai centrally located with modern engineering infrastructure and high placement percentage.",
        "base_cutoff": 90.00,
    },
    {
        "id": "dypit-pimpri",
        "name": "Dr. D. Y. Patil Institute of Technology (DYPIT Pimpri)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Pimpri, Pune, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.4,
        "nirf_rank": 165,
        "established": 1998,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Separate Boys & Girls Hostels)",
        "fees": 130000,
        "fee_display": "₹1.3 Lakh / year",
        "placement_avg": "₹6.8 LPA",
        "highest_package": "₹43.0 LPA",
        "top_recruiters": ["Amazon", "TCS", "Wipro", "Cognizant", "Capgemini", "Accenture"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "DYPIT Pimpri is an NAAC A++ accredited autonomous engineering college located in the industrial heartland of PCMC, Pune.",
        "base_cutoff": 88.50,
    },
    {
        "id": "frcrce-mumbai",
        "name": "Fr. Conceicao Rodrigues College of Engineering (CRCE Bandra)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Bandra West, Mumbai, Maharashtra",
        "type": "Private Autonomous (Minority)",
        "rating": 4.4,
        "established": 1984,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available nearby (Hostel partnerships)",
        "fees": 155000,
        "fee_display": "₹1.55 Lakh / year",
        "placement_avg": "₹7.4 LPA",
        "highest_package": "₹32.0 LPA",
        "top_recruiters": ["TCS", "Accenture", "Capgemini", "Morgan Stanley", "Infosys"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Computer Science",
            "Mechanical Engineering"
        ],
        "highlights": "Fr. CRCE Bandra, located at Bandstand, Mumbai, has an illustrious alumni base and consistent recruitment by premier tech and financial firms.",
        "base_cutoff": 88.00,
    },
    {
        "id": "thakur-mumbai",
        "name": "Thakur College of Engineering and Technology (TCET Mumbai)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Kandivali East, Mumbai, Maharashtra",
        "type": "Private Autonomous (Hindi Linguistic Minority)",
        "rating": 4.3,
        "nirf_rank": 185,
        "established": 2001,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Separate Boys & Girls Hostels)",
        "fees": 145000,
        "fee_display": "₹1.45 Lakh / year",
        "placement_avg": "₹6.5 LPA",
        "highest_package": "₹30.0 LPA",
        "top_recruiters": ["Infosys", "TCS", "Accenture", "Cognizant", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "TCET Kandivali is an autonomous engineering institute in Mumbai celebrated for modern infrastructure, active student incubation cells, and high placement records.",
        "base_cutoff": 86.50,
    },
    {
        "id": "vit-wadala",
        "name": "Vidyalankar Institute of Technology (VIT Wadala)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Wadala East, Mumbai, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.3,
        "established": 1999,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostel partnerships)",
        "fees": 150000,
        "fee_display": "₹1.5 Lakh / year",
        "placement_avg": "₹6.5 LPA",
        "highest_package": "₹37.5 LPA",
        "top_recruiters": ["Reliance Jio", "TCS", "Infosys", "Capgemini", "Amazon"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Biomedical Engineering"
        ],
        "highlights": "VIT Wadala is an award-winning autonomous campus in Mumbai known for high-tech digital classrooms, international collaborations, and strong tech placements.",
        "base_cutoff": 85.50,
    },
    {
        "id": "aissms-coe",
        "name": "AISSMS College of Engineering (AISSMS COE Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Shivajinagar / Kennedy Road, Pune, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.3,
        "established": 1992,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Boys & Girls Hostels)",
        "fees": 135000,
        "fee_display": "₹1.35 Lakh / year",
        "placement_avg": "₹6.2 LPA",
        "highest_package": "₹28.0 LPA",
        "top_recruiters": ["TCS", "Cognizant", "Wipro", "L&T Infotech", "Godrej"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering",
            "Chemical Engineering"
        ],
        "highlights": "AISSMS COE in central Pune is one of Maharashtra's historic and esteemed autonomous engineering institutions with strong ties to manufacturing and IT hubs.",
        "base_cutoff": 84.50,
    },
    {
        "id": "dypiemr-akurdi",
        "name": "Dr. D. Y. Patil Institute of Engineering, Management & Research (DYPIEMR Akurdi)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Akurdi, Pune, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.3,
        "established": 2012,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Separate Boys & Girls Hostels)",
        "fees": 125000,
        "fee_display": "₹1.25 Lakh / year",
        "placement_avg": "₹6.0 LPA",
        "highest_package": "₹32.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Capgemini", "Accenture"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "DYPIEMR Akurdi is located on the vibrant DY Patil Educational Complex in PCMC, offering modern labs and solid career placements.",
        "base_cutoff": 83.50,
    },
    {
        "id": "rgit-mumbai",
        "name": "Rajiv Gandhi Institute of Technology (RGIT Mumbai)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Versova, Andheri West, Mumbai, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.2,
        "established": 1992,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Nearby Hostel Accommodations)",
        "fees": 120000,
        "fee_display": "₹1.2 Lakh / year",
        "placement_avg": "₹5.8 LPA",
        "highest_package": "₹22.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Tech Mahindra", "Cognizant"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering"
        ],
        "highlights": "RGIT Mumbai is located near Versova Beach in Andheri West, offering excellent faculty guidance and consistent mass recruitments by IT services leaders.",
        "base_cutoff": 83.00,
    },
    {
        "id": "sinhgad-vadgaon",
        "name": "Sinhgad College of Engineering (SCOE Vadgaon Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Vadgaon Budruk, Pune, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.2,
        "established": 1996,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Huge On-Campus Hostels with Mess)",
        "fees": 125000,
        "fee_display": "₹1.25 Lakh / year",
        "placement_avg": "₹5.8 LPA",
        "highest_package": "₹33.0 LPA",
        "top_recruiters": ["Accenture", "Cognizant", "TCS", "Capgemini", "Infosys"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering",
            "Chemical Engineering"
        ],
        "highlights": "SCOE Vadgaon is the flagship college of Sinhgad Technical Education Society (STES), housing sprawling sports facilities and vast campus placements.",
        "base_cutoff": 82.00,
    },
    {
        "id": "modern-coe-pune",
        "name": "Progressive Education Society's Modern College of Engineering (PES MCOE Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Shivajinagar, Pune, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.2,
        "established": 1999,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostels for Boys & Girls)",
        "fees": 115000,
        "fee_display": "₹1.15 Lakh / year",
        "placement_avg": "₹5.6 LPA",
        "highest_package": "₹24.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Persistent", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Electrical Engineering",
            "Mechanical Engineering"
        ],
        "highlights": "PES Modern College of Engineering in Shivajinagar, Pune, provides top-notch academic discipline and excellent urban connectivity near Pune Railway Station.",
        "base_cutoff": 81.20,
    },
    {
        "id": "mmcoe-pune",
        "name": "Marathwada Mitra Mandal's College of Engineering (MMCOE Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Karvenagar, Pune, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.2,
        "established": 2006,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostels with Mess)",
        "fees": 120000,
        "fee_display": "₹1.2 Lakh / year",
        "placement_avg": "₹5.5 LPA",
        "highest_package": "₹26.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Capgemini", "Cognizant", "Persistent"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Electrical Engineering"
        ],
        "highlights": "MMCOE Karvenagar, Pune, is an accredited autonomous engineering college known for tech competitions, robotics labs, and steady placements.",
        "base_cutoff": 81.00,
    },
    {
        "id": "jspm-tathawade",
        "name": "JSPM's Rajarshi Shahu College of Engineering (RSCOE Tathawade Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Tathawade, Wakad, Pune, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.2,
        "established": 2001,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Separate Boys & Girls Hostels)",
        "fees": 125000,
        "fee_display": "₹1.25 Lakh / year",
        "placement_avg": "₹5.6 LPA",
        "highest_package": "₹40.0 LPA",
        "top_recruiters": ["TCS", "Wipro", "Infosys", "Capgemini", "Cognizant", "Accenture"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "RSCOE Tathawade is an autonomous engineering college situated right next to the Hinjawadi IT Park, providing students direct industry exposure.",
        "base_cutoff": 80.50,
    },
    {
        "id": "pillai-navi-mumbai",
        "name": "Pillai College of Engineering (PCE New Panvel)",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "location": "New Panvel, Navi Mumbai, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.1,
        "established": 1999,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Hostels)",
        "fees": 140000,
        "fee_display": "₹1.4 Lakh / year",
        "placement_avg": "₹5.5 LPA",
        "highest_package": "₹22.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Capgemini", "L&T Infotech", "Reliance Jio"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Automobile Engineering"
        ],
        "highlights": "Pillai College of Engineering in New Panvel is a leading autonomous campus in Navi Mumbai with vibrant research culture and high placement rates.",
        "base_cutoff": 79.50,
    },
    {
        "id": "dbit-mumbai",
        "name": "Don Bosco Institute of Technology (DBIT Kurla Mumbai)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Kurla West, Mumbai, Maharashtra",
        "type": "Private Autonomous (Minority)",
        "rating": 4.1,
        "established": 2001,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available nearby",
        "fees": 135000,
        "fee_display": "₹1.35 Lakh / year",
        "placement_avg": "₹5.5 LPA",
        "highest_package": "₹24.0 LPA",
        "top_recruiters": ["Infosys", "TCS", "Capgemini", "LTI", "Morgan Stanley"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering"
        ],
        "highlights": "DBIT Kurla is well known for moral foundation, strict academic discipline, and proactive placement assistance in Mumbai.",
        "base_cutoff": 79.00,
    },
    {
        "id": "atharva-mumbai",
        "name": "Atharva College of Engineering (ACE Malad Mumbai)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Malad West, Mumbai, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.1,
        "established": 1999,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostels with Wi-Fi)",
        "fees": 130000,
        "fee_display": "₹1.3 Lakh / year",
        "placement_avg": "₹5.4 LPA",
        "highest_package": "₹26.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Tech Mahindra", "Accenture", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Electrical Engineering"
        ],
        "highlights": "Atharva College of Engineering in Malad West features an i-Lab, tech exhibitions, and consistent on-campus placement drives.",
        "base_cutoff": 77.00,
    },
    {
        "id": "terna-nerul",
        "name": "Terna Engineering College (TEC Nerul Navi Mumbai)",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "location": "Nerul, Navi Mumbai, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.1,
        "established": 1991,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostel facilities)",
        "fees": 135000,
        "fee_display": "₹1.35 Lakh / year",
        "placement_avg": "₹5.2 LPA",
        "highest_package": "₹21.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Reliance Jio", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "Terna Engineering College in Nerul is situated opposite the Nerul railway station, offering premier engineering programs and industry certifications.",
        "base_cutoff": 76.00,
    },
    {
        "id": "skncoe-pune",
        "name": "Smt. Kashibai Navale College of Engineering (SKNCOE Vadgaon Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Vadgaon Budruk, Pune, Maharashtra",
        "type": "Private Affiliated",
        "rating": 4.0,
        "established": 2001,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Hostels)",
        "fees": 110000,
        "fee_display": "₹1.1 Lakh / year",
        "placement_avg": "₹5.0 LPA",
        "highest_package": "₹28.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Accenture", "Cognizant", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering"
        ],
        "highlights": "SKNCOE Vadgaon is part of the Sinhgad Group, providing vast sports complexes, student clubs, and centralized placement drives.",
        "base_cutoff": 75.00,
    },
    {
        "id": "gh-raisoni-nagpur",
        "name": "G. H. Raisoni College of Engineering (GHRCEM Nagpur)",
        "city": "Nagpur",
        "state": "Maharashtra",
        "location": "CRPF Gate No. 3, Hingna Road, Digdoh Hills, Nagpur, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.1,
        "nirf_rank": 151,
        "established": 1996,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Boys & Girls Hostels)",
        "fees": 140000,
        "fee_display": "₹1.4 Lakh / year",
        "placement_avg": "₹5.4 LPA",
        "highest_package": "₹25.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Tech Mahindra", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "GHRCEM Nagpur is an autonomous engineering powerhouse in Vidarbha, ranked in NIRF and famous for patents, incubation, and placements.",
        "base_cutoff": 74.00,
    },
    {
        "id": "aiktc-panvel",
        "name": "Anjuman-I-Islam's Kalsekar Technical Campus (AIKTC New Panvel)",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "location": "New Panvel, Navi Mumbai, Maharashtra",
        "type": "Private (Muslim Minority)",
        "rating": 4.0,
        "established": 2011,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostel with Mess)",
        "fees": 105000,
        "fee_display": "₹1.05 Lakh / year",
        "placement_avg": "₹4.8 LPA",
        "highest_package": "₹18.0 LPA",
        "top_recruiters": ["TCS", "Wipro", "Infosys", "Reliance Jio", "LTI"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Civil Engineering"
        ],
        "highlights": "AIKTC New Panvel offers modern architectural and engineering facilities with dedicated faculty and affordable fee structures.",
        "base_cutoff": 71.00,
    },
    {
        "id": "ltce-navi-mumbai",
        "name": "Lokmanya Tilak College of Engineering (LTCE Navi Mumbai)",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "location": "Kopar Khairane, Navi Mumbai, Maharashtra",
        "type": "Private Affiliated",
        "rating": 4.0,
        "established": 1994,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available nearby",
        "fees": 120000,
        "fee_display": "₹1.2 Lakh / year",
        "placement_avg": "₹4.8 LPA",
        "highest_package": "₹18.0 LPA",
        "top_recruiters": ["TCS", "Capgemini", "Infosys", "Wipro", "Hexaware"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering"
        ],
        "highlights": "LTCE Kopar Khairane is situated in the central Navi Mumbai tech corridor, facilitating easy industry visits and campus hiring.",
        "base_cutoff": 70.00,
    },
    {
        "id": "zeal-pune",
        "name": "Zeal College of Engineering and Research (ZCOER Narhe Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Narhe, Pune, Maharashtra",
        "type": "Private Autonomous",
        "rating": 4.0,
        "established": 2007,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Hostels)",
        "fees": 105000,
        "fee_display": "₹1.05 Lakh / year",
        "placement_avg": "₹4.8 LPA",
        "highest_package": "₹24.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Capgemini", "Wipro", "Tech Mahindra"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering",
            "Electrical Engineering"
        ],
        "highlights": "Zeal College in Narhe, Pune, is an autonomous college with modern incubation centers, hackathons, and high recruiter engagement.",
        "base_cutoff": 68.00,
    },
    {
        "id": "saraswati-kharghar",
        "name": "Saraswati College of Engineering (SCOE Kharghar Navi Mumbai)",
        "city": "Navi Mumbai",
        "state": "Maharashtra",
        "location": "Kharghar, Navi Mumbai, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.9,
        "established": 2004,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostels with Mess)",
        "fees": 115000,
        "fee_display": "₹1.15 Lakh / year",
        "placement_avg": "₹4.6 LPA",
        "highest_package": "₹16.5 LPA",
        "top_recruiters": ["TCS", "Capgemini", "Wipro", "LTI", "Infosys"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Civil Engineering",
            "Mechanical Engineering"
        ],
        "highlights": "Saraswati College in Kharghar is renowned for its Civil and Computer departments, scenic green campus, and student development programs.",
        "base_cutoff": 67.00,
    },
    {
        "id": "trinity-pune",
        "name": "Trinity College of Engineering and Research (TCOER Kondhwa Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Kondhwa Saswad Road, Pune, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.9,
        "established": 2008,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Campus Hostels with Mess)",
        "fees": 95000,
        "fee_display": "₹95,000 / year",
        "placement_avg": "₹4.5 LPA",
        "highest_package": "₹20.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Accenture", "Zensar"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "Trinity College of Engineering in Kondhwa is part of KJ's Educational Institute, known for hands-on technical workshops and affordable fee structure.",
        "base_cutoff": 65.00,
    },
    {
        "id": "kc-thane",
        "name": "K. C. College of Engineering & Management Studies (KCCOE Thane)",
        "city": "Thane",
        "state": "Maharashtra",
        "location": "Kopri, Thane East, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.9,
        "established": 2001,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available nearby",
        "fees": 110000,
        "fee_display": "₹1.1 Lakh / year",
        "placement_avg": "₹4.5 LPA",
        "highest_package": "₹15.0 LPA",
        "top_recruiters": ["TCS", "Capgemini", "Infosys", "Wipro", "Hexaware"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication"
        ],
        "highlights": "KCCOE Thane is located minutes away from Thane railway station, offering high quality education and active industry-academia partnerships.",
        "base_cutoff": 64.00,
    },
    {
        "id": "nmiet-pune",
        "name": "Nutan Maharashtra Institute of Engineering and Technology (NMIET Talegaon Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Talegaon Dabhade, Pune, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.8,
        "established": 2008,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Hostels)",
        "fees": 95000,
        "fee_display": "₹95,000 / year",
        "placement_avg": "₹4.4 LPA",
        "highest_package": "₹18.0 LPA",
        "top_recruiters": ["TCS", "Wipro", "Infosys", "Capgemini", "Tata Motors"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering"
        ],
        "highlights": "NMIET Talegaon is situated along the Mumbai-Pune expressway near auto and industrial corridors with focused placement training.",
        "base_cutoff": 62.00,
    },
    {
        "id": "sb-jain-nagpur",
        "name": "S. B. Jain Institute of Technology, Management & Research (SBJITMR Nagpur)",
        "city": "Nagpur",
        "state": "Maharashtra",
        "location": "Katol Road, Nagpur, Maharashtra",
        "type": "Private Autonomous (Jain Minority)",
        "rating": 3.8,
        "established": 2008,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostels with Mess)",
        "fees": 105000,
        "fee_display": "₹1.05 Lakh / year",
        "placement_avg": "₹4.5 LPA",
        "highest_package": "₹17.5 LPA",
        "top_recruiters": ["TCS", "Infosys", "Tech Mahindra", "Wipro", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Electrical Engineering"
        ],
        "highlights": "SBJITMR Nagpur is an autonomous institute providing well-rounded academic curriculum and reliable career counseling in central India.",
        "base_cutoff": 60.00,
    },
    {
        "id": "dpcoe-pune",
        "name": "Dhole Patil College of Engineering (DPCOE Wagholi Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Wagholi, Pune, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.7,
        "established": 2008,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Campus Hostels)",
        "fees": 92000,
        "fee_display": "₹92,000 / year",
        "placement_avg": "₹4.2 LPA",
        "highest_package": "₹16.0 LPA",
        "top_recruiters": ["TCS", "Wipro", "Infosys", "Cognizant", "Amazon"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering",
            "Automobile Engineering"
        ],
        "highlights": "DPCOE Wagholi is located close to Pune's eastern IT corridor of Kharadi and EON Free Zone, facilitating active recruiter engagement.",
        "base_cutoff": 58.00,
    },
    {
        "id": "pvg-nashik",
        "name": "PVG's College of Engineering and Technology (PVG Nashik)",
        "city": "Nashik",
        "state": "Maharashtra",
        "location": "Meri Mhasrul, Dindori Road, Nashik, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.7,
        "established": 2010,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostel with Mess)",
        "fees": 85000,
        "fee_display": "₹85,000 / year",
        "placement_avg": "₹4.0 LPA",
        "highest_package": "₹14.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Datamatics", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering"
        ],
        "highlights": "PVG Nashik is an established engineering institute offering practical hands-on labs and dedicated placement training for north Maharashtra candidates.",
        "base_cutoff": 56.00,
    },
    {
        "id": "alard-pune",
        "name": "Alard College of Engineering and Management (Alard Hinjawadi Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Marunji, Hinjawadi Phase 2, Pune, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.6,
        "established": 2009,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Hostels with Mess)",
        "fees": 90000,
        "fee_display": "₹90,000 / year",
        "placement_avg": "₹4.0 LPA",
        "highest_package": "₹15.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Capgemini", "Tech Mahindra", "Wipro"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "Alard College is located directly in Hinjawadi, allowing students to network with software companies and participate in regular internship drives.",
        "base_cutoff": 54.00,
    },
    {
        "id": "universal-vasai",
        "name": "Universal College of Engineering (UCoE Vasai Mumbai)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Kaman, Vasai, Palghar, Maharashtra",
        "type": "Private (Gujarati Linguistic Minority)",
        "rating": 3.6,
        "established": 2012,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available nearby",
        "fees": 105000,
        "fee_display": "₹1.05 Lakh / year",
        "placement_avg": "₹4.0 LPA",
        "highest_package": "₹14.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Capgemini", "Wipro", "Hexaware"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Civil Engineering"
        ],
        "highlights": "UCoE Vasai features a serene campus with smart classrooms and tech clubs serving the western suburban corridor of Mumbai.",
        "base_cutoff": 52.00,
    },
    {
        "id": "moze-balewadi",
        "name": "Genba Sopanrao Moze College of Engineering (GSMCOE Balewadi Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Balewadi, Pune, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.5,
        "established": 1999,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Separate Boys & Girls Hostels)",
        "fees": 85000,
        "fee_display": "₹85,000 / year",
        "placement_avg": "₹3.8 LPA",
        "highest_package": "₹12.0 LPA",
        "top_recruiters": ["TCS", "Wipro", "Cognizant", "Capgemini", "Infosys"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "GSMCOE Balewadi is situated adjacent to Baner and Hinjawadi with accessible transport and good foundational engineering programs.",
        "base_cutoff": 49.00,
    },
    {
        "id": "viva-virar",
        "name": "VIVA Institute of Technology (VIVA Virar Mumbai)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "location": "Shirgaon, Virar East, Palghar, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.5,
        "established": 2009,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available nearby",
        "fees": 90000,
        "fee_display": "₹90,000 / year",
        "placement_avg": "₹3.8 LPA",
        "highest_package": "₹12.5 LPA",
        "top_recruiters": ["TCS", "Infosys", "Capgemini", "LTI", "Wipro"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "VIVA Institute of Technology in Virar provides extensive labs, sports grounds, and active campus placement support.",
        "base_cutoff": 48.00,
    },
    {
        "id": "isbm-pune",
        "name": "ISB&M School of Technology (ISB&M SOT Nande Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Nande, Pashan-Sus Road, Pune, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.4,
        "established": 2010,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Campus Hostels with Mess)",
        "fees": 82000,
        "fee_display": "₹82,000 / year",
        "placement_avg": "₹3.6 LPA",
        "highest_package": "₹11.0 LPA",
        "top_recruiters": ["TCS", "Wipro", "Infosys", "Capgemini", "Cognizant"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering"
        ],
        "highlights": "ISB&M School of Technology in Nande, Pune, offers a peaceful learning atmosphere with focused skill development and industry visits.",
        "base_cutoff": 44.00,
    },
    {
        "id": "siddhant-pune",
        "name": "Siddhant College of Engineering (SCOE Chakan Sudumbare Pune)",
        "city": "Pune",
        "state": "Maharashtra",
        "location": "Sudumbare, Chakan-Talegaon Road, Pune, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.3,
        "established": 2005,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Hostels)",
        "fees": 78000,
        "fee_display": "₹78,000 / year",
        "placement_avg": "₹3.5 LPA",
        "highest_package": "₹10.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Bajaj Auto", "Tata Motors"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "Siddhant College of Engineering is situated in the Chakan automobile belt, offering students practical plant exposure and tech mentorship.",
        "base_cutoff": 40.00,
    },
    {
        "id": "ideal-wada",
        "name": "Ideal Institute of Technology (IIT Wada Palghar)",
        "city": "Palghar",
        "state": "Maharashtra",
        "location": "Wada, Palghar, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.2,
        "established": 2013,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostel with Mess)",
        "fees": 72000,
        "fee_display": "₹72,000 / year",
        "placement_avg": "₹3.4 LPA",
        "highest_package": "₹9.5 LPA",
        "top_recruiters": ["TCS", "Wipro", "Infosys", "Capgemini", "Tech Mahindra"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "Ideal Institute of Technology in Wada provides affordable technical education with bus transport facilities and supportive faculty.",
        "base_cutoff": 38.00,
    },
    {
        "id": "bharat-badlapur",
        "name": "Bharat College of Engineering (BCOE Badlapur Thane)",
        "city": "Thane",
        "state": "Maharashtra",
        "location": "Kanhor, Badlapur West, Thane, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.2,
        "established": 2010,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available nearby",
        "fees": 75000,
        "fee_display": "₹75,000 / year",
        "placement_avg": "₹3.3 LPA",
        "highest_package": "₹9.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Hexaware", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "BCOE Badlapur is situated amidst peaceful surroundings with direct local train connectivity from Central Railway stations.",
        "base_cutoff": 36.00,
    },
    {
        "id": "theem-boisar",
        "name": "Theem College of Engineering (TCOE Boisar Palghar)",
        "city": "Palghar",
        "state": "Maharashtra",
        "location": "Betegaon, Boisar East, Palghar, Maharashtra",
        "type": "Private Affiliated (Muslim Minority)",
        "rating": 3.1,
        "established": 2009,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostel with Mess)",
        "fees": 70000,
        "fee_display": "₹70,000 / year",
        "placement_avg": "₹3.2 LPA",
        "highest_package": "₹8.5 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Jio", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "Theem College in Boisar is near the Tarapur MIDC industrial zone, providing mechanical, chemical, and software internships.",
        "base_cutoff": 35.00,
    },
    {
        "id": "jondhle-asangaon",
        "name": "Shivajirao S. Jondhle College of Engineering (SSJCOE Asangaon Thane)",
        "city": "Thane",
        "state": "Maharashtra",
        "location": "Asangaon, Shahapur, Thane, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.1,
        "established": 2007,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (On-Campus Hostels)",
        "fees": 68000,
        "fee_display": "₹68,000 / year",
        "placement_avg": "₹3.2 LPA",
        "highest_package": "₹8.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Tech Mahindra"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "SSJCOE Asangaon offers engineering degrees with direct rail links from Mumbai CST and suburban stations.",
        "base_cutoff": 34.00,
    },
    {
        "id": "ytiet-karjat",
        "name": "Yadavrao Tasgaonkar Institute of Engineering & Technology (YTIET Karjat)",
        "city": "Raigad",
        "state": "Maharashtra",
        "location": "Bhivpuri Road, Karjat, Raigad, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.0,
        "established": 2005,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available (Hostels with Mess)",
        "fees": 65000,
        "fee_display": "₹65,000 / year",
        "placement_avg": "₹3.0 LPA",
        "highest_package": "₹7.5 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Reliance"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "YTIET Karjat offers scenic educational surroundings near Bhivpuri Road with open admissions and institute-level quota support.",
        "base_cutoff": 32.00,
    },
    {
        "id": "dilkap-neral",
        "name": "Dilkap Research Institute of Engineering and Management Studies (DRIEMS Neral)",
        "city": "Raigad",
        "state": "Maharashtra",
        "location": "Mamdapur, Neral, Karjat, Raigad, Maharashtra",
        "type": "Private Affiliated",
        "rating": 3.0,
        "established": 2010,
        "timings": "8:30 AM – 5:00 PM (Monday to Saturday)",
        "hostel_availability": "Available nearby",
        "fees": 62000,
        "fee_display": "₹62,000 / year",
        "placement_avg": "₹3.0 LPA",
        "highest_package": "₹7.0 LPA",
        "top_recruiters": ["TCS", "Infosys", "Wipro", "Capgemini"],
        "exams": ["MHT-CET", "JEE Main"],
        "courses": [
            "Computer Science & Engineering",
            "Information Technology",
            "Artificial Intelligence & Data Science",
            "Electronics & Telecommunication",
            "Mechanical Engineering",
            "Civil Engineering"
        ],
        "highlights": "DRIEMS Neral provides accessible degree pathways, personalized student guidance, and direct admission options for engineering aspirants.",
        "base_cutoff": 31.00,
    },
]
